import { LucodearFileIcon } from '../../model';
import { lucodear } from '../utils';

export const files: LucodearFileIcon[] = lucodear('misc', [
  {
    name: 'idea',
    fileNames: [
      'idea',
      'ideas',
      'idea.md',
      'idea.txt',
      'ideas.md',
      'ideas.txt',
    ],
    fileExtensions: [
      'idea',
      'ideas',
      'idea/md',
      'idea/mdx',
      'idea/txt',
      'idea/html',
      'ideas/md',
      'ideas/mdx',
      'ideas/txt',
      'ideas/html',
      '_idea/md',
      '_idea/mdx',
      '_idea/txt',
      '_idea/html',
      '_ideas/md',
      '_ideas/mdx',
      '_ideas/txt',
      '_ideas/html',
      '.idea/md',
      '.idea/mdx',
      '.idea/txt',
      '.idea/html',
      '.ideas/md',
      '.ideas/mdx',
      '.ideas/txt',
      '.ideas/html',
      '~idea/md',
      '~idea/mdx',
      '~idea/txt',
      '~idea/html',
      '~ideas/md',
      '~ideas/mdx',
      '~ideas/txt',
      '~ideas/html',
      '=idea/md',
      '=idea/mdx',
      '=idea/txt',
      '=idea/html',
      '=ideas/md',
      '=ideas/mdx',
      '=ideas/txt',
      '=ideas/html',
      '@idea/md',
      '@idea/mdx',
      '@idea/txt',
      '@idea/html',
      '@ideas/md',
      '@ideas/mdx',
      '@ideas/txt',
      '@ideas/html',
      '!idea/md',
      '!idea/mdx',
      '!idea/txt',
      '!idea/html',
      '!ideas/md',
      '!ideas/mdx',
      '!ideas/txt',
      '!ideas/html',
      '💡/md',
      '💡/mdx',
      '💡/txt',
      '💡/html',
    ],
  },
  {
    name: 'illustrator',
    fileExtensions: ['ai'],
    light: true,
  },
  {
    name: 'photoshop',
    fileExtensions: ['psd'],
    light: true,
  },
  {
    name: 'pureref',
    fileExtensions: ['pur'],
    light: true,
  },
  {
    name: 'workflow',
    fileExtensions: ['workflow/yml', 'workflow/yaml'],
  },
] as LucodearFileIcon[]);
