import { LanguageIdentifier } from '../models';

/**
 * Defines icons for language ids
 */
export const languageIcons: LanguageIdentifier[] = [
    { id: 'git', icon: { name: 'git' } },
    { id: 'git-commit', icon: { name: 'git' } },
    { id: 'git-rebase', icon: { name: 'git' } },
    { id: 'c', icon: { name: 'c' } },
    { id: 'objective-c', icon: { name: 'c' } },
    { id: 'yaml', icon: { name: 'yaml' } },
    { id: 'xml', icon: { name: 'xml' } },
    { id: 'xquery', icon: { name: 'xml' } },
    { id: 'matlab', icon: { name: 'matlab' } },
    { id: 'makefile', icon: { name: 'settings' } },
    { id: 'shaderlab', icon: { name: 'shaderlab' } },
    { id: 'diff', icon: { name: 'diff' } },
    { id: 'java', icon: { name: 'java' } },
    { id: 'razor', icon: { name: 'razor' } },
    { id: 'python', icon: { name: 'python' } },
    { id: 'javascript', icon: { name: 'javascript' } },
    { id: 'typescript', icon: { name: 'typescript' } },
    { id: 'scala', icon: { name: 'scala' } },
    { id: 'handlebars', icon: { name: 'handlebars' } },
    { id: 'perl', icon: { name: 'perl' } },
    { id: 'perl6', icon: { name: 'perl' } },
    { id: 'haxe', icon: { name: 'haxe' } },
    { id: 'hxml', icon: { name: 'haxe' } },
    { id: 'puppet', icon: { name: 'puppet' } },
    { id: 'elixir', icon: { name: 'elixir' } },
    { id: 'livescript', icon: { name: 'livescript' } },
    { id: 'erlang', icon: { name: 'erlang' } },
    { id: 'twig', icon: { name: 'twig' } },
    { id: 'julia', icon: { name: 'julia' } },
    { id: 'elm', icon: { name: 'elm' } },
    { id: 'purescript', icon: { name: 'purescript' } },
    { id: 'stylus', icon: { name: 'stylus' } },
    { id: 'nunjucks', icon: { name: 'nunjucks' } },
    { id: 'pug', icon: { name: 'pug' } },
    { id: 'robotframework', icon: { name: 'robot' } },
    { id: 'sass', icon: { name: 'sass' } },
    { id: 'less', icon: { name: 'less' } },
    { id: 'css', icon: { name: 'css' } },
    { id: 'testOutput', icon: { name: 'visualstudio' } },
    { id: 'ng-template', icon: { name: 'angular' } },
    { id: 'graphql', icon: { name: 'graphql' } },
    { id: 'solidity', icon: { name: 'solidity' } },
    { id: 'autoit', icon: { name: 'autoit' } },
    { id: 'haml', icon: { name: 'haml' } },
    { id: 'yang', icon: { name: 'yang' } },
    { id: 'terraform', icon: { name: 'terraform' } },
    { id: 'applescript', icon: { name: 'applescript' } },
    { id: 'cake', icon: { name: 'cake' } },
    { id: 'cucumber', icon: { name: 'cucumber' } },
    { id: 'nim', icon: { name: 'nim' } },
    { id: 'nimble', icon: { name: 'nim' } },
    { id: 'apiblueprint', icon: { name: 'apiblueprint' } },
    { id: 'riot', icon: { name: 'riot' } },
    { id: 'postcss', icon: { name: 'postcss' } },
    { id: 'lang-cfml', icon: { name: 'coldfusion' } },
    { id: 'haskell', icon: { name: 'haskell' } },
    { id: 'cabal', icon: { name: 'cabal' } },
    { id: 'nix', icon: { name: 'nix' } },
    { id: 'ruby', icon: { name: 'ruby' } },
    { id: 'slim', icon: { name: 'slim' } },
    { id: 'php', icon: { name: 'php' } },
    { id: 'hack', icon: { name: 'hack' } }
];
