/**
 * Generates open folder icon variants from closed folder SVGs.
 *
 * For each `folder-{name}.svg` in the icons directory that has the canonical
 * structure (viewBox 16x16, id="folder", id="motive"), this script generates
 * the corresponding `folder-{name}-open.svg` by replacing the folder path's
 * `d` attribute with the canonical open folder path.
 *
 * This runs as part of the build pipeline.
 */

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { getAttribute, replaceAttribute } from '../../core/helpers/svg';

const ICONS_DIR = join(process.cwd(), 'icons');

/** Canonical 16x16 open folder path */
const OPEN_FOLDER_PATH =
  'M14.483 6H4.721a1 1 0 0 0-.949.684L2 12V5h12a1 1 0 0 0-1-1H7.562a1 1 0 0 1-.64-.232l-.644-.536A1 1 0 0 0 5.638 3H2a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h11l2.403-5.606A1 1 0 0 0 14.483 6';

/**
 * Files that are excluded from open variant generation.
 * These are either generated by other scripts or have special handling.
 */
const EXCLUDED_FILES = new Set([
  'folder.svg', // Generated dynamically by generateFolderIcons with custom color
  'folder-root.svg', // Generated dynamically by generateRootFolderIcons
]);

/**
 * Check if a file is a closed folder SVG that needs an open variant generated.
 */
function isClosedFolderSvg(fileName: string): boolean {
  return (
    fileName.startsWith('folder-') &&
    fileName.endsWith('.svg') &&
    !/-open([_.])/.test(fileName) &&
    !fileName.endsWith('.clone.svg') &&
    !EXCLUDED_FILES.has(fileName)
  );
}

/**
 * Derive the open variant filename from a closed folder SVG filename.
 * Examples:
 *   folder-src.svg          -> folder-src-open.svg
 *   folder-git_light.svg    -> folder-git-open_light.svg
 *   folder-git_highContrast.svg -> folder-git-open_highContrast.svg
 */
function getOpenFileName(closedFileName: string): string {
  const suffixMatch = closedFileName.match(
    /^(folder-.+?)(_(light|highContrast))?\.svg$/
  );
  if (!suffixMatch) {
    throw new Error(`Unexpected filename format: ${closedFileName}`);
  }

  const baseName = suffixMatch[1];
  const themeSuffix = suffixMatch[2] || '';
  return `${baseName}-open${themeSuffix}.svg`;
}

/**
 * Generate the open variant of a closed folder SVG.
 */
async function generateOpenVariant(
  closedFilePath: string,
  openFilePath: string
): Promise<{ success: boolean; error?: string }> {
  try {
    const content = await readFile(closedFilePath, 'utf8');

    // Verify structure
    const [viewBox] = await getAttribute(content, 'svg', 'viewBox');
    if (viewBox !== '0 0 16 16') {
      return {
        success: false,
        error: `Unexpected viewBox: ${viewBox}`,
      };
    }

    const [folderD] = await getAttribute(content, '#folder', 'd');
    if (!folderD) {
      return {
        success: false,
        error: 'No element with id="folder" found',
      };
    }

    // Replace the folder path with the open variant
    const output = await replaceAttribute(
      content,
      '#folder',
      'd',
      OPEN_FOLDER_PATH
    );
    await writeFile(openFilePath, output, 'utf8');

    return { success: true };
  } catch (err) {
    return {
      success: false,
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

/**
 * Main entry point.
 */
async function main() {
  const files = await readdir(ICONS_DIR);
  const closedFolderSvgs = files.filter(isClosedFolderSvg).sort();

  let generated = 0;
  let errors = 0;

  for (const closedFile of closedFolderSvgs) {
    const openFile = getOpenFileName(closedFile);
    const closedPath = join(ICONS_DIR, closedFile);
    const openPath = join(ICONS_DIR, openFile);

    const result = await generateOpenVariant(closedPath, openPath);

    if (result.success) {
      generated++;
    } else {
      console.error(`  Error generating ${openFile}: ${result.error}`);
      errors++;
    }
  }

  console.log(
    `Generated ${generated} open folder icon${generated !== 1 ? 's' : ''}`
  );

  if (errors > 0) {
    console.error(`${errors} error(s) during generation`);
    process.exit(1);
  }
}

main();
