/**
 * Structural validation for folder SVG icons.
 *
 * Enforces that all folder SVGs follow the canonical structure:
 * - viewBox="0 0 16 16"
 * - Exactly one element with id="folder" containing the correct folder path
 * - At least one element with id="motive"
 * - No Inkscape/Sodipodi metadata
 * - No stray -open.svg files in source (they should be generated)
 *
 * This check is strict and runs as part of CI.
 */

import { readdir, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { type INode, parse } from 'svgson';
import { green, red } from '../../helpers/painter';

const ICONS_DIR = join(process.cwd(), 'icons');

/** Canonical 16x16 closed folder path */
const CLOSED_FOLDER_PATH =
  'm6.922 3.768-.644-.536A1 1 0 0 0 5.638 3H2a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H7.562a1 1 0 0 1-.64-.232';

/**
 * Files that are excluded from structural checks.
 * These are generated by other scripts or have special handling.
 */
const EXCLUDED_FILES = new Set([
  'folder.svg',
  'folder-open.svg',
  'folder-root.svg',
  'folder-root-open.svg',
]);

interface ValidationError {
  file: string;
  errors: string[];
}

/**
 * Check if a file should be validated by this script.
 */
function shouldValidate(fileName: string): boolean {
  return (
    fileName.startsWith('folder-') &&
    fileName.endsWith('.svg') &&
    !fileName.includes('-open') &&
    !fileName.endsWith('.clone.svg') &&
    !EXCLUDED_FILES.has(fileName)
  );
}

/**
 * Find all elements with a given id in the SVG tree.
 */
function findElementsById(node: INode, id: string): INode[] {
  const results: INode[] = [];

  if (node.attributes?.id === id) {
    results.push(node);
  }

  if (node.children) {
    for (const child of node.children) {
      results.push(...findElementsById(child, id));
    }
  }

  return results;
}

/**
 * Check for Inkscape/Sodipodi metadata in the SVG tree.
 */
function hasInkscapeMetadata(node: INode): boolean {
  // Check attributes
  for (const key of Object.keys(node.attributes || {})) {
    if (
      key.startsWith('inkscape:') ||
      key.startsWith('sodipodi:') ||
      key.startsWith('xmlns:inkscape') ||
      key.startsWith('xmlns:sodipodi')
    ) {
      return true;
    }
  }

  // Check for sodipodi elements
  if (node.name === 'sodipodi:namedview' || node.name.startsWith('inkscape:')) {
    return true;
  }

  // Check children
  if (node.children) {
    for (const child of node.children) {
      if (hasInkscapeMetadata(child)) {
        return true;
      }
    }
  }

  return false;
}

/**
 * Validate a single folder SVG file.
 */
async function validateFile(
  filePath: string,
  fileName: string
): Promise<string[]> {
  const errors: string[] = [];

  try {
    const content = await readFile(filePath, 'utf8');
    const svg = await parse(content);

    // 1. Check viewBox
    if (svg.attributes.viewBox !== '0 0 16 16') {
      errors.push(
        `viewBox must be "0 0 16 16", found "${svg.attributes.viewBox || 'none'}"`
      );
    }

    // 2. Check for exactly one element with id="folder"
    const folderElements = findElementsById(svg, 'folder');
    if (folderElements.length === 0) {
      errors.push('Missing element with id="folder"');
    } else if (folderElements.length > 1) {
      errors.push(
        `Found ${folderElements.length} elements with id="folder", expected exactly 1`
      );
    } else {
      // 3. Verify the folder path is correct
      const folderEl = folderElements[0];
      if (folderEl.name !== 'path') {
        errors.push(
          `Element with id="folder" must be a <path>, found <${folderEl.name}>`
        );
      } else {
        const d = (folderEl.attributes.d || '').replace(/\s+/g, ' ').trim();
        if (d !== CLOSED_FOLDER_PATH) {
          errors.push(
            'Element with id="folder" has incorrect path data (must use the canonical closed folder path)'
          );
        }
      }
    }

    // 4. Check for at least one element with id="motive"
    const motiveElements = findElementsById(svg, 'motive');
    if (motiveElements.length === 0) {
      errors.push('Missing element with id="motive"');
    } else if (motiveElements.length > 1) {
      errors.push(
        `Found ${motiveElements.length} elements with id="motive", expected exactly 1`
      );
    }

    // 5. Check for Inkscape metadata
    if (hasInkscapeMetadata(svg)) {
      errors.push(
        'Contains Inkscape/Sodipodi metadata (please clean with SVGO or remove manually)'
      );
    }

    // 6. Check for xml declaration (not needed for SVG in this project)
    if (content.startsWith('<?xml')) {
      errors.push(
        'Contains XML declaration (<?xml ...?>), which should be removed'
      );
    }
  } catch (err) {
    errors.push(
      `Failed to parse: ${err instanceof Error ? err.message : String(err)}`
    );
  }

  return errors;
}

/**
 * Main entry point.
 */
export async function check(): Promise<void> {
  const files = await readdir(ICONS_DIR);
  const folderSvgs = files.filter(shouldValidate).sort();

  const validationErrors: ValidationError[] = [];

  for (const file of folderSvgs) {
    const filePath = join(ICONS_DIR, file);
    const errors = await validateFile(filePath, file);
    if (errors.length > 0) {
      validationErrors.push({ file, errors });
    }
  }

  if (validationErrors.length === 0) {
    console.log(
      '> Material Icon Theme:',
      green('Passed folder icon structure checks!')
    );
    return;
  }

  const totalErrors = validationErrors.reduce(
    (sum, v) => sum + v.errors.length,
    0
  );

  console.log(
    '> Material Icon Theme:',
    red(
      `Found ${totalErrors} structural error(s) in ${validationErrors.length} folder icon(s)!`
    )
  );

  console.log(
    '\nFolder icon structure errors:\n--------------------------------'
  );
  for (const { file, errors } of validationErrors) {
    console.log(red(`\n  ${file}:`));
    for (const error of errors) {
      console.log(`    - ${error}`);
    }
  }

  throw new Error(
    `Found structural errors in ${validationErrors.length} folder icon(s).`
  );
}

// Allow running directly
if (import.meta.path === Bun.main) {
  check().catch((err) => {
    process.exit(1);
  });
}
