/**
 * Structural validation for folder SVG icons.
 *
 * Enforces that all folder SVGs follow the canonical structure:
 * - viewBox="0 0 16 16"
 * - Exactly one element with id="folder" containing the correct folder path
 * - At least one element with id="motive"
 * - No Inkscape/Sodipodi metadata
 * - No stray -open.svg files in source (they should be generated)
 *
 * This check is strict and runs as part of CI.
 */

import { readdir, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import {
  countElements,
  getAttribute,
  getElements,
  hasAttributeMatching,
  hasElementMatching,
} from '../../../core/helpers/svg';
import { green, red } from '../../helpers/painter';

const ICONS_DIR = join(process.cwd(), 'icons');

/** Canonical 16x16 closed folder path */
const CLOSED_FOLDER_PATH =
  'm6.922 3.768-.644-.536A1 1 0 0 0 5.638 3H2a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H7.562a1 1 0 0 1-.64-.232';

/**
 * Files that are excluded from structural checks.
 * These are generated by other scripts or have special handling.
 */
const EXCLUDED_FILES = new Set([
  'folder.svg',
  'folder-open.svg',
  'folder-root.svg',
  'folder-root-open.svg',
]);

interface ValidationError {
  file: string;
  errors: string[];
}

/**
 * Check if a file should be validated by this script.
 */
function shouldValidate(fileName: string): boolean {
  return (
    fileName.startsWith('folder-') &&
    fileName.endsWith('.svg') &&
    !fileName.includes('-open') &&
    !fileName.endsWith('.clone.svg') &&
    !EXCLUDED_FILES.has(fileName)
  );
}

/**
 * Validate a folder SVG's content against the structural requirements.
 * Returns an array of error messages (empty if valid).
 */
export async function validateFolderSvg(content: string): Promise<string[]> {
  const errors: string[] = [];

  // 1. Check for XML declaration
  if (content.startsWith('<?xml')) {
    errors.push(
      'Contains XML declaration (<?xml ...?>), which should be removed'
    );
  }

  // 2. Check viewBox
  const [viewBox] = await getAttribute(content, 'svg', 'viewBox');
  if (viewBox !== '0 0 16 16') {
    errors.push(`viewBox must be "0 0 16 16", found "${viewBox || 'none'}"`);
  }

  // 3. Check for exactly one element with id="folder"
  const folderCount = await countElements(content, '#folder');
  if (folderCount === 0) {
    errors.push('Missing element with id="folder"');
  } else if (folderCount > 1) {
    errors.push(
      `Found ${folderCount} elements with id="folder", expected exactly 1`
    );
  } else {
    // 4. Verify the folder element is a path with correct d
    const [folder] = await getElements(content, '#folder');
    if (folder.tagName !== 'path') {
      errors.push(
        `Element with id="folder" must be a <path>, found <${folder.tagName}>`
      );
    } else {
      const d = (folder.attributes.d || '').replace(/\s+/g, ' ').trim();
      if (d !== CLOSED_FOLDER_PATH) {
        errors.push(
          'Element with id="folder" has incorrect path data (must use the canonical closed folder path)'
        );
      }
    }
  }

  // 5. Check for at least one element with id="motive"
  const motiveCount = await countElements(content, '#motive');
  if (motiveCount === 0) {
    errors.push('Missing element with id="motive"');
  } else if (motiveCount > 1) {
    errors.push(
      `Found ${motiveCount} elements with id="motive", expected exactly 1`
    );
  }

  // 6. Check for Inkscape metadata
  const hasInkscapeAttrs = await hasAttributeMatching(
    content,
    '*',
    (name) =>
      name.startsWith('inkscape:') ||
      name.startsWith('sodipodi:') ||
      name.startsWith('xmlns:inkscape') ||
      name.startsWith('xmlns:sodipodi')
  );
  if (hasInkscapeAttrs) {
    errors.push(
      'Contains Inkscape/Sodipodi metadata (please clean with SVGO or remove manually)'
    );
  }

  const hasInkscapeElements = await hasElementMatching(
    content,
    '*',
    (tagName) => tagName.includes('sodipodi') || tagName.includes('inkscape')
  );
  if (hasInkscapeElements) {
    errors.push('Contains Inkscape/Sodipodi elements (please remove manually)');
  }

  return errors;
}

/**
 * Main entry point.
 */
export async function check(): Promise<void> {
  const files = await readdir(ICONS_DIR);
  const folderSvgs = files.filter(shouldValidate).sort();

  const validationErrors: ValidationError[] = [];

  for (const file of folderSvgs) {
    const filePath = join(ICONS_DIR, file);
    const content = await readFile(filePath, 'utf8');
    const errors = await validateFolderSvg(content);
    if (errors.length > 0) {
      validationErrors.push({ file, errors });
    }
  }

  if (validationErrors.length === 0) {
    console.log(
      '> Material Icon Theme:',
      green('Passed folder icon structure checks!')
    );
    return;
  }

  const totalErrors = validationErrors.reduce(
    (sum, v) => sum + v.errors.length,
    0
  );

  console.log(
    '> Material Icon Theme:',
    red(
      `Found ${totalErrors} structural error(s) in ${validationErrors.length} folder icon(s)!`
    )
  );

  console.log(
    '\nFolder icon structure errors:\n--------------------------------'
  );
  for (const { file, errors } of validationErrors) {
    console.log(red(`\n  ${file}:`));
    for (const error of errors) {
      console.log(`    - ${error}`);
    }
  }

  throw new Error(
    `Found structural errors in ${validationErrors.length} folder icon(s).`
  );
}

// Allow running directly
if (import.meta.path === Bun.main) {
  check().catch(() => {
    process.exit(1);
  });
}
