name: 🏞️ Icon Request
description: Ask for specific icons to be added
title: "[Icon Request]: <icon_name>"
labels: ["icon-request"]

body:
  - type: checkboxes
    id: icon-type
    attributes:
      label: Icon Type
      description: What type of icon are you requesting?
      options:
        - label: Folder
        - label: File

  - type: textarea
    id: folder-names
    attributes:
      label: Folder names
      description: If you are requesting folder icons, please list the folder names here.
      placeholder: |
        - folder-name
        - another-folder-name
        - ...

  - type: textarea
    id: file-names
    attributes:
      label: File names
      description: If you are requesting file icons, please list the file names or file extensions here.
      placeholder: |
        - file-name
        - another-file-name
        - ...

  - type: textarea
    id: graphic-ideas
    attributes:
      label: Graphic ideas
      description: |
        A clear description of the icon you would like.
        If the icons are separate for folder and files, please create separate issues.
      placeholder: Include a link to sample icons if possible

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the icons here.
      placeholder: I consider these icons necessary because ...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../../CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's **Code of Conduct**
          required: true
