name: Icon Request.
description: Ask for specific icons to be added
title: "[Icon Request]: <icon_name>"
labels: ["icon-request"]

body:
  - type: checkboxes
    id: icon-type
    attributes:
      label: Icon Type
      options:
        - label: Folder
        - label: File
          required: true

  - type: textarea
    id: folder-names
    attributes:
      label: Folder names
      placeholder: |
        - folder-name
        - another-folder-name
        - ...
    validations:
      required: false

  - type: textarea
    id: file-names
    attributes:
      label: File names
      placeholder: |
        - file-name
        - another-file-name
        - ...
    validations:
      required: false

  - type: textarea
    id: graphic-ideas
    attributes:
      label: Graphic ideas
      description: A clear description of the icon you would like. If the icons are separate for folder and files, please create separate issues.
      placeholder: Include a link to sample icons if possible
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the icons here.
      placeholder: I consider these icons necessary because ...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../../CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's **Code of Conduct**
          required: true
