name: 🛠️ Build + Test

on:
  push:
    paths:
      - 'build/**'
      - 'icons/*.svg'
      - 'patches/**'
      - 'src/**'
      - '.bun-version'
      - 'bunfig.toml'
      - 'package.json'
      - 'bun.lock'
      - 'sheriff.config.ts'
      - '!*.md'

  pull_request:
    paths:
      - 'build/**'
      - 'icons/*.svg'
      - 'patches/**'
      - 'src/**'
      - '.bun-version'
      - 'bunfig.toml'
      - 'package.json'
      - 'bun.lock'
      - 'sheriff.config.ts'
      - '!*.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    name: Build & Test Extension

    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: 🔧 Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version-file: ".bun-version"

      - name: 📦 Install dependencies
        run: bun install --frozen-lockfile

      - name: 🚀 Test + Build
        id: build
        run: |
          bun test
          bun run vscode:prepublish
