name: 🎨 Check SVG icon colors

on:
  pull_request:
    paths:
      - "icons/*.svg"

permissions:
  contents: read
  pull-requests: write

jobs:
  color-check:
    name: SVG Color Check

    runs-on: ubuntu-latest

    env:
      TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            material-colors.yml
            icons/

      - name: 🔄 Fetch target branch
        run: |
          git fetch origin $TARGET_BRANCH

      - name: 🎨 Check colors
        id: color-check
        run: |
          svgFiles=$(git diff origin/$TARGET_BRANCH --diff-filter=ACMRTUX  --name-only | grep '.svg$')
          npx svg-color-linter --config material-colors.yml ${svgFiles}
