# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.

name: 🔖 Labeler

on: [pull_request_target]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    name: Label

    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
