name: 🎉 PR closed

on:
  pull_request_target:
    types:
      - closed

permissions:
  contents: read
  pull-requests: write

jobs:
  thank-you:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: 🙏 Post Thank You Comment
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              ## Merge Successful

              Thanks for your contribution! 🎉

              The changes will be part of the upcoming update on the Marketplace.`
            })
